export const CHANGE_INTTERVIEW_TYPE = "CHANGE_INTTERVIEW_TYPE";
export const INTERVIEW_REQUEST = "INTERVIEW_REQUEST";
export const INTERVIEW_FAILIURE = "INTERVIEW_FAILIURE";
export const INTERVIEW_START_POST_REQUEST = "INTERVIEW_START_POST_REQUEST";
export const INTERVIEW_UPDATE_PATCH_REQUEST = "INTERVIEW_UPDATE_PATCH_REQUEST";
export const INTERVIEW_GET_DATA_REQUEST = "INTERVIEW_GET_DATA_REQUEST";
export const INTERVIEW_END_POST_REQUEST = "INTERVIEW_END_POST_REQUEST";
